// ============================================================
// MediCore ERP - Mock Data for Development
// ============================================================

import {
  UserRole, Gender, AppointmentType, AppointmentStatus, Priority,
  InvoiceStatus, PaymentMethod, LeadStatus, LeadSource, TreatmentCategory, TaxCategory,
  WorkflowStage, LabTestStatus, DocumentType, RoomType, RoomStatus,
  type Branch, type User, type Patient, type Appointment, type Treatment,
  type Invoice, type Payment, type Lead, type CallLog, type FollowUp,
  type Room, type ConsultationNote, type Prescription, type LabTest,
  type Package, type Triage, type Notification, type AuditLog,
  type AITranscription, type PatientDocument, type CommunicationLog,
  type SkinHistory, type MedicalHistory, type ActivityItem, type PatientPackage,
  type RoomAllocation,
} from "@/types";

// ---- Branches ----
export const mockBranches: Branch[] = [
  { id: "br-001", name: "MediCore Main Clinic", code: "MAIN", address: "123 Medical Plaza, Downtown", phone: "(555) 100-0001", email: "main@medicore.com", isActive: true, createdAt: "2024-01-15" },
  { id: "br-002", name: "MediCore Downtown", code: "DT", address: "456 City Center Ave", phone: "(555) 100-0002", email: "downtown@medicore.com", isActive: true, createdAt: "2024-03-01" },
  { id: "br-003", name: "MediCore Westside", code: "WS", address: "789 West Blvd, Suite 200", phone: "(555) 100-0003", email: "westside@medicore.com", isActive: true, createdAt: "2024-06-15" },
  { id: "br-004", name: "MediCore North", code: "N", address: "321 North Park Dr", phone: "(555) 100-0004", email: "north@medicore.com", isActive: true, createdAt: "2025-01-01" },
  { id: "br-005", name: "MediCore South", code: "S", address: "654 South Gate Mall", phone: "(555) 100-0005", email: "south@medicore.com", isActive: false, createdAt: "2025-06-01" },
];

// ---- Users / Staff ----
export const mockUsers: User[] = [
  { id: "usr-001", email: "admin@medicore.com", name: "Dr. Sarah Mitchell", phone: "(555) 201-0001", role: UserRole.ADMIN, branchId: "br-001", branchName: "Main Clinic", isActive: true, lastLogin: "2026-04-05T08:30:00", createdAt: "2024-01-15" },
  { id: "usr-002", email: "dr.chen@medicore.com", name: "Dr. Emily Chen", phone: "(555) 201-0002", role: UserRole.DOCTOR, branchId: "br-001", branchName: "Main Clinic", isActive: true, lastLogin: "2026-04-05T07:45:00", createdAt: "2024-01-20" },
  { id: "usr-003", email: "dr.patel@medicore.com", name: "Dr. Raj Patel", phone: "(555) 201-0003", role: UserRole.DOCTOR, branchId: "br-001", branchName: "Main Clinic", isActive: true, lastLogin: "2026-04-05T08:00:00", createdAt: "2024-02-01" },
  { id: "usr-004", email: "dr.kim@medicore.com", name: "Dr. Lisa Kim", phone: "(555) 201-0004", role: UserRole.DOCTOR, branchId: "br-002", branchName: "Downtown", isActive: true, lastLogin: "2026-04-04T17:30:00", createdAt: "2024-03-15" },
  { id: "usr-005", email: "reception@medicore.com", name: "Maria Santos", phone: "(555) 201-0005", role: UserRole.RECEPTIONIST, branchId: "br-001", branchName: "Main Clinic", isActive: true, lastLogin: "2026-04-05T07:55:00", createdAt: "2024-01-20" },
  { id: "usr-006", email: "billing@medicore.com", name: "James Wilson", phone: "(555) 201-0006", role: UserRole.BILLING, branchId: "br-001", branchName: "Main Clinic", isActive: true, lastLogin: "2026-04-05T08:10:00", createdAt: "2024-02-15" },
  { id: "usr-007", email: "callcenter@medicore.com", name: "Sophie Taylor", phone: "(555) 201-0007", role: UserRole.CALL_CENTER, branchId: "br-001", branchName: "Main Clinic", isActive: true, lastLogin: "2026-04-05T08:00:00", createdAt: "2024-04-01" },
  { id: "usr-008", email: "nurse@medicore.com", name: "Rachel Green", phone: "(555) 201-0008", role: UserRole.ASSISTANT, branchId: "br-001", branchName: "Main Clinic", isActive: true, lastLogin: "2026-04-05T07:50:00", createdAt: "2024-03-01" },
  { id: "usr-009", email: "dr.williams@medicore.com", name: "Dr. Mark Williams", phone: "(555) 201-0009", role: UserRole.DOCTOR, branchId: "br-003", branchName: "Westside", isActive: true, lastLogin: "2026-04-04T16:00:00", createdAt: "2024-06-20" },
  { id: "usr-010", email: "superadmin@medicore.com", name: "Alex Thompson", phone: "(555) 201-0010", role: UserRole.SUPER_ADMIN, branchId: "br-001", branchName: "Main Clinic", isActive: true, lastLogin: "2026-04-05T09:00:00", createdAt: "2024-01-01" },
];

// ---- Patients ----
export const mockPatients: Patient[] = [
  { id: "pt-001", patientCode: "PT-0001", firstName: "Olivia", lastName: "Harper", email: "olivia.h@email.com", phone: "(555) 301-0001", dateOfBirth: "1992-05-14", age: 33, gender: Gender.FEMALE, address: "45 Oak Street", city: "Westville", emergencyContact: "David Harper", emergencyPhone: "(555) 301-0099", bloodType: "O+", branchId: "br-001", branchName: "Main Clinic", assignedDoctorId: "usr-002", assignedDoctorName: "Dr. Emily Chen", isActive: true, allergies: ["Salicylic Acid", "Latex"], skinType: "TYPE_III", lastVisit: "2026-03-28", nextAppointment: "2026-04-05", outstandingBalance: 250, createdAt: "2025-01-10" },
  { id: "pt-002", patientCode: "PT-0002", firstName: "Ethan", lastName: "Brooks", email: "ethan.b@email.com", phone: "(555) 301-0002", dateOfBirth: "1988-11-22", age: 37, gender: Gender.MALE, address: "78 Pine Avenue", city: "Downtown", emergencyContact: "Sarah Brooks", emergencyPhone: "(555) 301-0098", bloodType: "A+", branchId: "br-001", branchName: "Main Clinic", assignedDoctorId: "usr-003", assignedDoctorName: "Dr. Raj Patel", isActive: true, allergies: ["Retinol"], skinType: "TYPE_II", lastVisit: "2026-04-01", nextAppointment: "2026-04-05", outstandingBalance: 0, createdAt: "2025-02-05" },
  { id: "pt-003", patientCode: "PT-0003", firstName: "Sophia", lastName: "Martinez", email: "sophia.m@email.com", phone: "(555) 301-0003", dateOfBirth: "1995-08-30", age: 30, gender: Gender.FEMALE, address: "22 Maple Lane", city: "Northside", emergencyContact: "Carlos Martinez", emergencyPhone: "(555) 301-0097", bloodType: "B+", branchId: "br-001", branchName: "Main Clinic", assignedDoctorId: "usr-002", assignedDoctorName: "Dr. Emily Chen", isActive: true, allergies: [], skinType: "TYPE_IV", lastVisit: "2026-04-03", nextAppointment: "2026-04-07", outstandingBalance: 180, createdAt: "2025-01-20" },
  { id: "pt-004", patientCode: "PT-0004", firstName: "Liam", lastName: "Johnson", email: "liam.j@email.com", phone: "(555) 301-0004", dateOfBirth: "1985-03-17", age: 41, gender: Gender.MALE, address: "110 Cedar Rd", city: "Westville", emergencyContact: "Amy Johnson", emergencyPhone: "(555) 301-0096", bloodType: "AB+", branchId: "br-002", branchName: "Downtown", assignedDoctorId: "usr-004", assignedDoctorName: "Dr. Lisa Kim", isActive: true, allergies: ["Hydroquinone", "Benzoyl Peroxide"], skinType: "TYPE_II", lastVisit: "2026-03-25", nextAppointment: "2026-04-10", outstandingBalance: 500, createdAt: "2025-03-15" },
  { id: "pt-005", patientCode: "PT-0005", firstName: "Ava", lastName: "Williams", email: "ava.w@email.com", phone: "(555) 301-0005", dateOfBirth: "1999-12-05", age: 26, gender: Gender.FEMALE, address: "55 Birch Street", city: "Eastside", emergencyContact: "Tom Williams", emergencyPhone: "(555) 301-0095", bloodType: "O-", branchId: "br-001", branchName: "Main Clinic", assignedDoctorId: "usr-003", assignedDoctorName: "Dr. Raj Patel", isActive: true, allergies: [], skinType: "TYPE_V", lastVisit: "2026-04-04", nextAppointment: "2026-04-05", outstandingBalance: 0, createdAt: "2025-04-01" },
  { id: "pt-006", patientCode: "PT-0006", firstName: "Noah", lastName: "Davis", email: "noah.d@email.com", phone: "(555) 301-0006", dateOfBirth: "1990-07-21", age: 35, gender: Gender.MALE, address: "300 Elm Dr", city: "Downtown", emergencyContact: "Karen Davis", emergencyPhone: "(555) 301-0094", bloodType: "A-", branchId: "br-001", branchName: "Main Clinic", assignedDoctorId: "usr-002", assignedDoctorName: "Dr. Emily Chen", isActive: true, allergies: ["AHA"], skinType: "TYPE_I", lastVisit: "2026-03-30", outstandingBalance: 75, createdAt: "2025-02-20" },
  { id: "pt-007", patientCode: "PT-0007", firstName: "Isabella", lastName: "Garcia", email: "isabella.g@email.com", phone: "(555) 301-0007", dateOfBirth: "1993-01-10", age: 33, gender: Gender.FEMALE, address: "88 Walnut Ave", city: "Southside", emergencyContact: "Miguel Garcia", emergencyPhone: "(555) 301-0093", bloodType: "B-", branchId: "br-002", branchName: "Downtown", assignedDoctorId: "usr-004", assignedDoctorName: "Dr. Lisa Kim", isActive: true, allergies: ["Fragrance"], skinType: "TYPE_IV", lastVisit: "2026-04-02", nextAppointment: "2026-04-06", outstandingBalance: 0, createdAt: "2025-05-10" },
  { id: "pt-008", patientCode: "PT-0008", firstName: "Mason", lastName: "Brown", email: "mason.b@email.com", phone: "(555) 301-0008", dateOfBirth: "1987-09-03", age: 38, gender: Gender.MALE, address: "42 Spruce Ct", city: "Westville", emergencyContact: "Linda Brown", emergencyPhone: "(555) 301-0092", bloodType: "O+", branchId: "br-003", branchName: "Westside", assignedDoctorId: "usr-009", assignedDoctorName: "Dr. Mark Williams", isActive: true, allergies: [], skinType: "TYPE_III", lastVisit: "2026-03-20", outstandingBalance: 320, createdAt: "2025-01-05" },
  { id: "pt-009", patientCode: "PT-0009", firstName: "Emma", lastName: "Wilson", email: "emma.w@email.com", phone: "(555) 301-0009", dateOfBirth: "1997-04-28", age: 28, gender: Gender.FEMALE, address: "15 Ash Blvd", city: "Northside", emergencyContact: "Paul Wilson", emergencyPhone: "(555) 301-0091", bloodType: "A+", branchId: "br-001", branchName: "Main Clinic", assignedDoctorId: "usr-003", assignedDoctorName: "Dr. Raj Patel", isActive: true, allergies: ["Nickel"], skinType: "TYPE_II", lastVisit: "2026-04-04", nextAppointment: "2026-04-05", outstandingBalance: 0, createdAt: "2025-06-15" },
  { id: "pt-010", patientCode: "PT-0010", firstName: "Charlotte", lastName: "Lee", email: "charlotte.l@email.com", phone: "(555) 301-0010", dateOfBirth: "1991-06-12", age: 34, gender: Gender.FEMALE, address: "200 Cherry Lane", city: "Eastside", emergencyContact: "Robert Lee", emergencyPhone: "(555) 301-0090", bloodType: "AB-", branchId: "br-001", branchName: "Main Clinic", assignedDoctorId: "usr-002", assignedDoctorName: "Dr. Emily Chen", isActive: true, allergies: ["Vitamin C serum"], skinType: "TYPE_VI", lastVisit: "2026-04-01", nextAppointment: "2026-04-08", outstandingBalance: 150, createdAt: "2025-03-01" },
  { id: "pt-011", patientCode: "PT-0011", firstName: "James", lastName: "Anderson", email: "james.a@email.com", phone: "(555) 301-0011", dateOfBirth: "1983-02-14", age: 43, gender: Gender.MALE, address: "67 Poplar Way", city: "Downtown", emergencyContact: "Monica Anderson", emergencyPhone: "(555) 301-0089", bloodType: "O+", branchId: "br-002", branchName: "Downtown", assignedDoctorId: "usr-004", assignedDoctorName: "Dr. Lisa Kim", isActive: true, allergies: [], skinType: "TYPE_I", lastVisit: "2026-03-15", outstandingBalance: 0, createdAt: "2025-07-01" },
  { id: "pt-012", patientCode: "PT-0012", firstName: "Mia", lastName: "Thomas", email: "mia.t@email.com", phone: "(555) 301-0012", dateOfBirth: "1996-10-08", age: 29, gender: Gender.FEMALE, address: "33 Willow St", city: "Southside", emergencyContact: "Chris Thomas", emergencyPhone: "(555) 301-0088", bloodType: "B+", branchId: "br-001", branchName: "Main Clinic", assignedDoctorId: "usr-002", assignedDoctorName: "Dr. Emily Chen", isActive: false, allergies: ["Glycolic Acid"], skinType: "TYPE_III", lastVisit: "2026-01-10", outstandingBalance: 0, createdAt: "2025-08-20" },
  { id: "pt-013", patientCode: "PT-0013", firstName: "Benjamin", lastName: "Taylor", email: "ben.t@email.com", phone: "(555) 301-0013", dateOfBirth: "1994-08-19", age: 31, gender: Gender.MALE, address: "99 Magnolia Blvd", city: "Westville", emergencyContact: "Jennifer Taylor", emergencyPhone: "(555) 301-0087", bloodType: "A+", branchId: "br-001", branchName: "Main Clinic", assignedDoctorId: "usr-003", assignedDoctorName: "Dr. Raj Patel", isActive: true, allergies: [], skinType: "TYPE_III", lastVisit: "2026-04-03", nextAppointment: "2026-04-12", outstandingBalance: 0, createdAt: "2025-04-15" },
  { id: "pt-014", patientCode: "PT-0014", firstName: "Amelia", lastName: "Moore", email: "amelia.m@email.com", phone: "(555) 301-0014", dateOfBirth: "1989-12-25", age: 36, gender: Gender.FEMALE, address: "171 Ivy Circle", city: "Northside", emergencyContact: "Greg Moore", emergencyPhone: "(555) 301-0086", bloodType: "O+", branchId: "br-003", branchName: "Westside", assignedDoctorId: "usr-009", assignedDoctorName: "Dr. Mark Williams", isActive: true, allergies: ["Parabens"], skinType: "TYPE_II", lastVisit: "2026-03-29", nextAppointment: "2026-04-05", outstandingBalance: 420, createdAt: "2025-05-01" },
  { id: "pt-015", patientCode: "PT-0015", firstName: "Lucas", lastName: "Jackson", email: "lucas.j@email.com", phone: "(555) 301-0015", dateOfBirth: "2000-03-07", age: 26, gender: Gender.MALE, address: "58 Hazel Rd", city: "Eastside", emergencyContact: "Diana Jackson", emergencyPhone: "(555) 301-0085", bloodType: "AB+", branchId: "br-001", branchName: "Main Clinic", assignedDoctorId: "usr-002", assignedDoctorName: "Dr. Emily Chen", isActive: true, allergies: [], skinType: "TYPE_IV", lastVisit: "2026-04-04", nextAppointment: "2026-04-05", outstandingBalance: 0, createdAt: "2025-09-01" },
  { id: "pt-016", patientCode: "PT-0016", firstName: "Harper", lastName: "White", email: "harper.w@email.com", phone: "(555) 301-0016", dateOfBirth: "1998-06-30", age: 27, gender: Gender.FEMALE, address: "82 Dogwood Ln", city: "Downtown", emergencyContact: "Mark White", emergencyPhone: "(555) 301-0084", bloodType: "B-", branchId: "br-001", branchName: "Main Clinic", assignedDoctorId: "usr-003", assignedDoctorName: "Dr. Raj Patel", isActive: true, allergies: ["Sulfur"], skinType: "TYPE_I", lastVisit: "2026-04-02", outstandingBalance: 0, createdAt: "2025-10-15" },
  { id: "pt-017", patientCode: "PT-0017", firstName: "Alexander", lastName: "Harris", email: "alex.h@email.com", phone: "(555) 301-0017", dateOfBirth: "1986-11-11", age: 39, gender: Gender.MALE, address: "444 Cypress Ave", city: "Southside", emergencyContact: "Nancy Harris", emergencyPhone: "(555) 301-0083", bloodType: "A-", branchId: "br-002", branchName: "Downtown", assignedDoctorId: "usr-004", assignedDoctorName: "Dr. Lisa Kim", isActive: true, allergies: [], skinType: "TYPE_III", lastVisit: "2026-03-18", outstandingBalance: 200, createdAt: "2025-06-20" },
  { id: "pt-018", patientCode: "PT-0018", firstName: "Ella", lastName: "Clark", email: "ella.c@email.com", phone: "(555) 301-0018", dateOfBirth: "2001-02-15", age: 25, gender: Gender.FEMALE, address: "19 Redwood St", city: "Westville", emergencyContact: "Steven Clark", emergencyPhone: "(555) 301-0082", bloodType: "O+", branchId: "br-001", branchName: "Main Clinic", assignedDoctorId: "usr-002", assignedDoctorName: "Dr. Emily Chen", isActive: true, allergies: ["Tea Tree Oil"], skinType: "TYPE_V", lastVisit: "2026-04-04", nextAppointment: "2026-04-05", outstandingBalance: 0, createdAt: "2025-11-01" },
  { id: "pt-019", patientCode: "PT-0019", firstName: "Daniel", lastName: "Lewis", email: "daniel.l@email.com", phone: "(555) 301-0019", dateOfBirth: "1992-09-22", age: 33, gender: Gender.MALE, address: "263 Juniper Dr", city: "Northside", emergencyContact: "Laura Lewis", emergencyPhone: "(555) 301-0081", bloodType: "A+", branchId: "br-003", branchName: "Westside", assignedDoctorId: "usr-009", assignedDoctorName: "Dr. Mark Williams", isActive: true, allergies: [], skinType: "TYPE_II", lastVisit: "2026-03-22", outstandingBalance: 0, createdAt: "2025-07-10" },
  { id: "pt-020", patientCode: "PT-0020", firstName: "Grace", lastName: "Robinson", email: "grace.r@email.com", phone: "(555) 301-0020", dateOfBirth: "1995-04-03", age: 30, gender: Gender.FEMALE, address: "77 Sequoia Blvd", city: "Downtown", emergencyContact: "Kevin Robinson", emergencyPhone: "(555) 301-0080", bloodType: "B+", branchId: "br-001", branchName: "Main Clinic", assignedDoctorId: "usr-003", assignedDoctorName: "Dr. Raj Patel", isActive: true, allergies: ["Lanolin"], skinType: "TYPE_III", lastVisit: "2026-04-03", nextAppointment: "2026-04-09", outstandingBalance: 95, createdAt: "2025-12-01" },
];

// ---- Appointments (Today + This Week) ----
const today = "2026-04-05";
export const mockAppointments: Appointment[] = [
  { id: "apt-001", appointmentCode: "APT-0001", patientId: "pt-001", patientName: "Olivia Harper", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Clinic", roomId: "rm-001", roomName: "Room 1", date: today, startTime: "09:00", endTime: "09:30", type: AppointmentType.FOLLOW_UP, status: AppointmentStatus.COMPLETED, priority: Priority.NORMAL, workflowStage: WorkflowStage.HISTORY_UPDATE, createdBy: "usr-005", createdAt: "2026-03-28", notes: "Follow-up on acne treatment progress" },
  { id: "apt-002", appointmentCode: "APT-0002", patientId: "pt-002", patientName: "Ethan Brooks", doctorId: "usr-003", doctorName: "Dr. Raj Patel", branchId: "br-001", branchName: "Main Clinic", roomId: "rm-002", roomName: "Room 2", date: today, startTime: "09:00", endTime: "09:45", type: AppointmentType.PROCEDURE, status: AppointmentStatus.IN_PROGRESS, priority: Priority.NORMAL, workflowStage: WorkflowStage.TREATMENT, createdBy: "usr-005", createdAt: "2026-03-30", notes: "Laser resurfacing session 3 of 6" },
  { id: "apt-003", appointmentCode: "APT-0003", patientId: "pt-005", patientName: "Ava Williams", doctorId: "usr-003", doctorName: "Dr. Raj Patel", branchId: "br-001", branchName: "Main Clinic", date: today, startTime: "10:00", endTime: "10:30", type: AppointmentType.CONSULTATION, status: AppointmentStatus.WAITING, priority: Priority.NORMAL, workflowStage: WorkflowStage.WAITING, createdBy: "usr-005", createdAt: "2026-04-01", notes: "New consultation for hyperpigmentation" },
  { id: "apt-004", appointmentCode: "APT-0004", patientId: "pt-009", patientName: "Emma Wilson", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Clinic", date: today, startTime: "10:00", endTime: "10:30", type: AppointmentType.CONSULTATION, status: AppointmentStatus.CHECKED_IN, priority: Priority.NORMAL, workflowStage: WorkflowStage.CHECKIN, checkinTime: "09:52", createdBy: "usr-005", createdAt: "2026-04-02", notes: "Rosacea assessment" },
  { id: "apt-005", appointmentCode: "APT-0005", patientId: "pt-015", patientName: "Lucas Jackson", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Clinic", date: today, startTime: "10:30", endTime: "11:15", type: AppointmentType.PROCEDURE, status: AppointmentStatus.CONFIRMED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-007", createdAt: "2026-04-03", notes: "Microneedling session" },
  { id: "apt-006", appointmentCode: "APT-0006", patientId: "pt-018", patientName: "Ella Clark", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Clinic", date: today, startTime: "11:00", endTime: "11:30", type: AppointmentType.FOLLOW_UP, status: AppointmentStatus.CONFIRMED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-04-03" },
  { id: "apt-007", appointmentCode: "APT-0007", patientId: "pt-014", patientName: "Amelia Moore", doctorId: "usr-009", doctorName: "Dr. Mark Williams", branchId: "br-003", branchName: "Westside", date: today, startTime: "09:30", endTime: "10:15", type: AppointmentType.PROCEDURE, status: AppointmentStatus.IN_PROGRESS, priority: Priority.NORMAL, workflowStage: WorkflowStage.TREATMENT, createdBy: "usr-005", createdAt: "2026-03-29", notes: "Chemical peel - glycolic acid" },
  { id: "apt-008", appointmentCode: "APT-0008", patientId: "pt-003", patientName: "Sophia Martinez", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Clinic", date: today, startTime: "11:30", endTime: "12:00", type: AppointmentType.REVIEW, status: AppointmentStatus.SCHEDULED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-04-01" },
  { id: "apt-009", appointmentCode: "APT-0009", patientId: "pt-006", patientName: "Noah Davis", doctorId: "usr-003", doctorName: "Dr. Raj Patel", branchId: "br-001", branchName: "Main Clinic", date: today, startTime: "11:00", endTime: "11:45", type: AppointmentType.PROCEDURE, status: AppointmentStatus.SCHEDULED, priority: Priority.URGENT, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-04-04", notes: "IPL treatment for sun damage" },
  { id: "apt-010", appointmentCode: "APT-0010", patientId: "pt-010", patientName: "Charlotte Lee", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Clinic", date: today, startTime: "14:00", endTime: "14:30", type: AppointmentType.CONSULTATION, status: AppointmentStatus.SCHEDULED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-007", createdAt: "2026-04-04" },
  { id: "apt-011", appointmentCode: "APT-0011", patientId: "pt-013", patientName: "Benjamin Taylor", doctorId: "usr-003", doctorName: "Dr. Raj Patel", branchId: "br-001", branchName: "Main Clinic", date: today, startTime: "14:00", endTime: "14:45", type: AppointmentType.PROCEDURE, status: AppointmentStatus.SCHEDULED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-04-02", notes: "Botox - forehead and crow's feet" },
  { id: "apt-012", appointmentCode: "APT-0012", patientId: "pt-016", patientName: "Harper White", doctorId: "usr-003", doctorName: "Dr. Raj Patel", branchId: "br-001", branchName: "Main Clinic", date: today, startTime: "15:00", endTime: "15:30", type: AppointmentType.FOLLOW_UP, status: AppointmentStatus.SCHEDULED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-04-03" },
  { id: "apt-013", appointmentCode: "APT-0013", patientId: "pt-020", patientName: "Grace Robinson", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Clinic", date: today, startTime: "15:00", endTime: "15:30", type: AppointmentType.CONSULTATION, status: AppointmentStatus.SCHEDULED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-007", createdAt: "2026-04-04" },
  { id: "apt-014", appointmentCode: "APT-0014", patientId: "pt-001", patientName: "Olivia Harper", doctorId: "usr-002", doctorName: "Dr. Emily Chen", branchId: "br-001", branchName: "Main Clinic", date: "2026-04-07", startTime: "09:00", endTime: "09:30", type: AppointmentType.FOLLOW_UP, status: AppointmentStatus.SCHEDULED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-04-05" },
  { id: "apt-015", appointmentCode: "APT-0015", patientId: "pt-004", patientName: "Liam Johnson", doctorId: "usr-004", doctorName: "Dr. Lisa Kim", branchId: "br-002", branchName: "Downtown", date: "2026-04-10", startTime: "10:00", endTime: "10:45", type: AppointmentType.PROCEDURE, status: AppointmentStatus.SCHEDULED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-04-01", notes: "Dermal filler session" },
  // Cancelled / No-show
  { id: "apt-016", appointmentCode: "APT-0016", patientId: "pt-011", patientName: "James Anderson", doctorId: "usr-004", doctorName: "Dr. Lisa Kim", branchId: "br-002", branchName: "Downtown", date: today, startTime: "09:00", endTime: "09:30", type: AppointmentType.CONSULTATION, status: AppointmentStatus.NO_SHOW, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-03-28" },
  { id: "apt-017", appointmentCode: "APT-0017", patientId: "pt-008", patientName: "Mason Brown", doctorId: "usr-009", doctorName: "Dr. Mark Williams", branchId: "br-003", branchName: "Westside", date: today, startTime: "11:00", endTime: "11:30", type: AppointmentType.FOLLOW_UP, status: AppointmentStatus.CANCELLED, priority: Priority.NORMAL, workflowStage: WorkflowStage.BOOKED, createdBy: "usr-005", createdAt: "2026-03-25", notes: "Patient requested cancellation" },
];

// ---- Treatments Catalog ----
export const mockTreatments: Treatment[] = [
  { id: "trt-001", name: "Fractional CO2 Laser", category: TreatmentCategory.LASER, taxCategory: TaxCategory.COSMETIC, description: "Precision laser for skin resurfacing, acne scars, and wrinkles", duration: 45, basePrice: 450, isActive: true },
  { id: "trt-002", name: "IPL Photofacial", category: TreatmentCategory.LASER, taxCategory: TaxCategory.COSMETIC, description: "Intense pulsed light for sun damage, pigmentation, and redness", duration: 30, basePrice: 300, isActive: true },
  { id: "trt-003", name: "Glycolic Acid Peel", category: TreatmentCategory.CHEMICAL_PEEL, taxCategory: TaxCategory.COSMETIC, description: "Medium-depth peel for acne, pigmentation, and skin texture", duration: 30, basePrice: 150, isActive: true },
  { id: "trt-004", name: "TCA Peel", category: TreatmentCategory.CHEMICAL_PEEL, taxCategory: TaxCategory.COSMETIC, description: "Deep chemical peel for scarring and severe sun damage", duration: 45, basePrice: 250, isActive: true },
  { id: "trt-005", name: "HydraFacial", category: TreatmentCategory.FACIAL, taxCategory: TaxCategory.COSMETIC, description: "Deep cleansing, exfoliation, extraction, and hydration", duration: 60, basePrice: 200, isActive: true },
  { id: "trt-006", name: "LED Light Therapy", category: TreatmentCategory.FACIAL, taxCategory: TaxCategory.COSMETIC, description: "Red and blue light therapy for acne and anti-aging", duration: 20, basePrice: 75, isActive: true },
  { id: "trt-007", name: "Botox", category: TreatmentCategory.INJECTABLE, taxCategory: TaxCategory.COSMETIC, description: "Botulinum toxin for wrinkle reduction", duration: 30, basePrice: 350, isActive: true },
  { id: "trt-008", name: "Dermal Fillers", category: TreatmentCategory.INJECTABLE, taxCategory: TaxCategory.COSMETIC, description: "Hyaluronic acid fillers for volume and contour", duration: 45, basePrice: 500, isActive: true },
  { id: "trt-009", name: "Microneedling + PRP", category: TreatmentCategory.OTHER, taxCategory: TaxCategory.COSMETIC, description: "Collagen induction with platelet-rich plasma", duration: 60, basePrice: 400, isActive: true },
  { id: "trt-010", name: "Cryotherapy", category: TreatmentCategory.OTHER, taxCategory: TaxCategory.MEDICAL, description: "Freezing treatment for warts, skin tags, and lesions", duration: 15, basePrice: 100, isActive: true },
  { id: "trt-011", name: "Mole Removal", category: TreatmentCategory.SURGICAL, taxCategory: TaxCategory.MEDICAL, description: "Surgical excision or shave removal of moles", duration: 30, basePrice: 250, isActive: true },
  { id: "trt-012", name: "PRP Hair Restoration", category: TreatmentCategory.INJECTABLE, taxCategory: TaxCategory.COSMETIC, description: "Platelet-rich plasma injections for hair loss", duration: 45, basePrice: 600, isActive: true },
];

// ---- Invoices ----
export const mockInvoices: Invoice[] = [
  { id: "inv-001", invoiceNumber: "INV-2026-0001", patientId: "pt-001", patientName: "Olivia Harper", branchId: "br-001", items: [{ description: "Follow-up Consultation", quantity: 1, unitPrice: 100, total: 100 }, { description: "Sunscreen SPF 50", quantity: 1, unitPrice: 45, total: 45 }], subtotal: 145, discount: 0, discountType: "FIXED", tax: 10.15, total: 155.15, status: InvoiceStatus.PAID, dueDate: "2026-03-28", payments: [], createdById: "usr-006", createdAt: "2026-03-28" },
  { id: "inv-002", invoiceNumber: "INV-2026-0002", patientId: "pt-002", patientName: "Ethan Brooks", branchId: "br-001", appointmentId: "apt-002", items: [{ description: "Fractional CO2 Laser - Session 3", quantity: 1, unitPrice: 450, total: 450 }], subtotal: 450, discount: 0, discountType: "FIXED", tax: 31.50, total: 481.50, status: InvoiceStatus.PENDING, dueDate: "2026-04-05", payments: [], createdById: "usr-006", createdAt: "2026-04-05" },
  { id: "inv-003", invoiceNumber: "INV-2026-0003", patientId: "pt-003", patientName: "Sophia Martinez", branchId: "br-001", items: [{ description: "HydraFacial", quantity: 1, unitPrice: 200, total: 200 }, { description: "Consultation Fee", quantity: 1, unitPrice: 100, total: 100 }], subtotal: 300, discount: 20, discountType: "PERCENTAGE", tax: 16.80, total: 256.80, status: InvoiceStatus.PARTIAL, dueDate: "2026-04-10", payments: [], createdById: "usr-006", createdAt: "2026-04-03" },
  { id: "inv-004", invoiceNumber: "INV-2026-0004", patientId: "pt-004", patientName: "Liam Johnson", branchId: "br-002", items: [{ description: "Botox - Forehead + Crow's Feet", quantity: 1, unitPrice: 350, total: 350 }, { description: "Dermal Filler - Nasolabial", quantity: 1, unitPrice: 500, total: 500 }], subtotal: 850, discount: 50, discountType: "FIXED", tax: 56, total: 856, status: InvoiceStatus.OVERDUE, dueDate: "2026-03-25", payments: [], createdById: "usr-006", createdAt: "2026-03-20" },
  { id: "inv-005", invoiceNumber: "INV-2026-0005", patientId: "pt-005", patientName: "Ava Williams", branchId: "br-001", items: [{ description: "Consultation - Hyperpigmentation", quantity: 1, unitPrice: 100, total: 100 }], subtotal: 100, discount: 0, discountType: "FIXED", tax: 7, total: 107, status: InvoiceStatus.PENDING, dueDate: "2026-04-12", payments: [], createdById: "usr-006", createdAt: "2026-04-05" },
  { id: "inv-006", invoiceNumber: "INV-2026-0006", patientId: "pt-006", patientName: "Noah Davis", branchId: "br-001", items: [{ description: "IPL Photofacial", quantity: 1, unitPrice: 300, total: 300 }], subtotal: 300, discount: 0, discountType: "FIXED", tax: 21, total: 321, status: InvoiceStatus.PAID, dueDate: "2026-03-30", payments: [], createdById: "usr-006", createdAt: "2026-03-30" },
  { id: "inv-007", invoiceNumber: "INV-2026-0007", patientId: "pt-007", patientName: "Isabella Garcia", branchId: "br-002", items: [{ description: "Glycolic Acid Peel", quantity: 1, unitPrice: 150, total: 150 }, { description: "LED Light Therapy", quantity: 1, unitPrice: 75, total: 75 }], subtotal: 225, discount: 0, discountType: "FIXED", tax: 15.75, total: 240.75, status: InvoiceStatus.PAID, dueDate: "2026-04-02", payments: [], createdById: "usr-006", createdAt: "2026-04-02" },
  { id: "inv-008", invoiceNumber: "INV-2026-0008", patientId: "pt-008", patientName: "Mason Brown", branchId: "br-003", items: [{ description: "Microneedling + PRP", quantity: 1, unitPrice: 400, total: 400 }], subtotal: 400, discount: 0, discountType: "FIXED", tax: 28, total: 428, status: InvoiceStatus.OVERDUE, dueDate: "2026-03-27", payments: [], createdById: "usr-006", createdAt: "2026-03-20" },
  { id: "inv-009", invoiceNumber: "INV-2026-0009", patientId: "pt-009", patientName: "Emma Wilson", branchId: "br-001", items: [{ description: "Consultation - Rosacea", quantity: 1, unitPrice: 100, total: 100 }, { description: "Prescription Cream", quantity: 1, unitPrice: 35, total: 35 }], subtotal: 135, discount: 0, discountType: "FIXED", tax: 9.45, total: 144.45, status: InvoiceStatus.PAID, dueDate: "2026-04-04", payments: [], createdById: "usr-006", createdAt: "2026-04-04" },
  { id: "inv-010", invoiceNumber: "INV-2026-0010", patientId: "pt-010", patientName: "Charlotte Lee", branchId: "br-001", items: [{ description: "Glow Package - Session 4 of 6", quantity: 1, unitPrice: 0, total: 0 }], subtotal: 0, discount: 0, discountType: "FIXED", tax: 0, total: 0, status: InvoiceStatus.PAID, dueDate: "2026-04-01", payments: [], createdById: "usr-006", createdAt: "2026-04-01", notes: "Package deduction" },
  { id: "inv-011", invoiceNumber: "INV-2026-0011", patientId: "pt-014", patientName: "Amelia Moore", branchId: "br-003", items: [{ description: "TCA Peel", quantity: 1, unitPrice: 250, total: 250 }, { description: "Post-peel care kit", quantity: 1, unitPrice: 65, total: 65 }], subtotal: 315, discount: 15, discountType: "PERCENTAGE", tax: 18.74, total: 286.49, status: InvoiceStatus.PENDING, dueDate: "2026-04-12", payments: [], createdById: "usr-006", createdAt: "2026-04-05" },
  { id: "inv-012", invoiceNumber: "INV-2026-0012", patientId: "pt-017", patientName: "Alexander Harris", branchId: "br-002", items: [{ description: "Cryotherapy - Skin Tags (3)", quantity: 3, unitPrice: 100, total: 300 }], subtotal: 300, discount: 50, discountType: "FIXED", tax: 17.50, total: 267.50, status: InvoiceStatus.DRAFT, dueDate: "2026-04-15", payments: [], createdById: "usr-006", createdAt: "2026-04-05" },
];

// ---- Leads ----
export const mockLeads: Lead[] = [
  { id: "ld-001", name: "Rebecca Stone", phone: "(555) 401-0001", email: "rebecca.s@email.com", source: LeadSource.CALL, status: LeadStatus.NEW, interest: "Acne Treatment", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-001", notes: "Called asking about acne treatment options", createdAt: "2026-04-05T09:15:00", updatedAt: "2026-04-05T09:15:00" },
  { id: "ld-002", name: "Michael Foster", phone: "(555) 401-0002", source: LeadSource.WEBSITE, status: LeadStatus.CONTACTED, interest: "Anti-aging", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-001", notes: "Filled form on website, interested in Botox", callbackDate: "2026-04-06T10:00:00", createdAt: "2026-04-04T14:30:00", updatedAt: "2026-04-05T08:00:00" },
  { id: "ld-003", name: "Jessica Wright", phone: "(555) 401-0003", email: "jess.w@email.com", source: LeadSource.SOCIAL_MEDIA, status: LeadStatus.INTERESTED, interest: "Laser Treatment", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-001", notes: "Saw Instagram post about laser resurfacing, very interested", callbackDate: "2026-04-05T14:00:00", createdAt: "2026-04-03T11:00:00", updatedAt: "2026-04-04T16:00:00" },
  { id: "ld-004", name: "Andrew Kim", phone: "(555) 401-0004", source: LeadSource.REFERRAL, status: LeadStatus.BOOKED, interest: "Hair Loss", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-001", notes: "Referred by pt-002 (Ethan Brooks), booked PRP consultation", convertedPatientId: "pt-021", createdAt: "2026-04-02T09:00:00", updatedAt: "2026-04-04T10:00:00" },
  { id: "ld-005", name: "Diana Murphy", phone: "(555) 401-0005", source: LeadSource.WALK_IN, status: LeadStatus.NOT_INTERESTED, interest: "Chemical Peel", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-002", notes: "Walked in to ask about pricing, said too expensive", createdAt: "2026-04-01T15:30:00", updatedAt: "2026-04-01T16:00:00" },
  { id: "ld-006", name: "Thomas Reed", phone: "(555) 401-0006", email: "tom.r@email.com", source: LeadSource.CALL, status: LeadStatus.FOLLOW_UP, interest: "Scar Treatment", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-001", notes: "Wants more info about scar revision options", callbackDate: "2026-04-07T11:00:00", createdAt: "2026-04-03T13:00:00", updatedAt: "2026-04-05T09:00:00" },
  { id: "ld-007", name: "Sandra Mitchell", phone: "(555) 401-0007", source: LeadSource.WEBSITE, status: LeadStatus.NEW, interest: "Skin Check", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-003", createdAt: "2026-04-05T08:30:00", updatedAt: "2026-04-05T08:30:00" },
  { id: "ld-008", name: "Kevin Park", phone: "(555) 401-0008", source: LeadSource.SOCIAL_MEDIA, status: LeadStatus.CONTACTED, interest: "HydraFacial", assignedToId: "usr-007", assignedToName: "Sophie Taylor", branchId: "br-001", notes: "TikTok inquiry about HydraFacial packages", callbackDate: "2026-04-05T16:00:00", createdAt: "2026-04-04T10:00:00", updatedAt: "2026-04-04T15:00:00" },
];

// ---- Packages ----
export const mockPackages: Package[] = [
  { id: "pkg-001", name: "Glow Up Package", description: "6 HydraFacials + 3 Chemical Peels for complete skin rejuvenation", treatments: [{ treatmentId: "trt-005", name: "HydraFacial", sessions: 6 }, { treatmentId: "trt-003", name: "Glycolic Acid Peel", sessions: 3 }], price: 1500, validityDays: 180, isActive: true, subscriberCount: 12, createdAt: "2025-06-01" },
  { id: "pkg-002", name: "Acne Clear Plan", description: "10 targeted sessions combining LED therapy and chemical peels", treatments: [{ treatmentId: "trt-006", name: "LED Light Therapy", sessions: 6 }, { treatmentId: "trt-003", name: "Glycolic Acid Peel", sessions: 4 }], price: 800, validityDays: 120, isActive: true, subscriberCount: 8, createdAt: "2025-07-15" },
  { id: "pkg-003", name: "Anti-Aging Premium", description: "Botox + Fillers + Laser for comprehensive anti-aging", treatments: [{ treatmentId: "trt-007", name: "Botox", sessions: 2 }, { treatmentId: "trt-008", name: "Dermal Fillers", sessions: 1 }, { treatmentId: "trt-001", name: "Fractional CO2 Laser", sessions: 3 }], price: 3200, validityDays: 365, isActive: true, subscriberCount: 5, createdAt: "2025-09-01" },
  { id: "pkg-004", name: "Hair Restore Bundle", description: "4 PRP sessions for hair restoration", treatments: [{ treatmentId: "trt-012", name: "PRP Hair Restoration", sessions: 4 }], price: 2000, validityDays: 180, isActive: true, subscriberCount: 3, createdAt: "2025-10-01" },
  { id: "pkg-005", name: "Monthly Maintenance", description: "Monthly HydraFacial + LED combo for ongoing skin health", treatments: [{ treatmentId: "trt-005", name: "HydraFacial", sessions: 12 }, { treatmentId: "trt-006", name: "LED Light Therapy", sessions: 12 }], price: 2400, validityDays: 365, isActive: true, subscriberCount: 15, createdAt: "2025-11-01" },
];

// ---- Rooms ----
export const mockRooms: Room[] = [
  { id: "rm-001", branchId: "br-001", name: "Room 1 - Consultation", type: RoomType.CONSULTATION, status: RoomStatus.OCCUPIED, isAvailable: false, capacity: 2, currentPatientName: "Olivia Harper", currentDoctorName: "Dr. Emily Chen", occupiedSince: "2026-04-05T09:00:00" },
  { id: "rm-002", branchId: "br-001", name: "Room 2 - Laser Suite", type: RoomType.PROCEDURE, status: RoomStatus.OCCUPIED, isAvailable: false, capacity: 3, currentPatientName: "Ethan Brooks", currentDoctorName: "Dr. Raj Patel", occupiedSince: "2026-04-05T09:00:00" },
  { id: "rm-003", branchId: "br-001", name: "Room 3 - Procedure", type: RoomType.PROCEDURE, status: RoomStatus.AVAILABLE, isAvailable: true, capacity: 2 },
  { id: "rm-004", branchId: "br-001", name: "Room 4 - Consultation", type: RoomType.CONSULTATION, status: RoomStatus.CLEANING, isAvailable: false, capacity: 2 },
  { id: "rm-005", branchId: "br-001", name: "Room 5 - Recovery", type: RoomType.RECOVERY, status: RoomStatus.AVAILABLE, isAvailable: true, capacity: 4 },
  { id: "rm-006", branchId: "br-001", name: "Waiting Area", type: RoomType.WAITING, status: RoomStatus.AVAILABLE, isAvailable: true, capacity: 15 },
  { id: "rm-007", branchId: "br-002", name: "Room 1 - Consultation", type: RoomType.CONSULTATION, status: RoomStatus.AVAILABLE, isAvailable: true, capacity: 2 },
  { id: "rm-008", branchId: "br-002", name: "Room 2 - Procedure", type: RoomType.PROCEDURE, status: RoomStatus.MAINTENANCE, isAvailable: false, capacity: 3 },
  { id: "rm-009", branchId: "br-003", name: "Room 1 - Multi-Purpose", type: RoomType.PROCEDURE, status: RoomStatus.OCCUPIED, isAvailable: false, capacity: 3, currentPatientName: "Amelia Moore", currentDoctorName: "Dr. Mark Williams", occupiedSince: "2026-04-05T09:30:00" },
  { id: "rm-010", branchId: "br-003", name: "Room 2 - Consultation", type: RoomType.CONSULTATION, status: RoomStatus.AVAILABLE, isAvailable: true, capacity: 2 },
];

// ---- Follow-Ups ----
export const mockFollowUps: FollowUp[] = [
  { id: "fu-001", patientId: "pt-001", patientName: "Olivia Harper", doctorId: "usr-002", doctorName: "Dr. Emily Chen", dueDate: "2026-04-07", reason: "Check acne treatment progress after 2 weeks", status: "PENDING", createdAt: "2026-03-28" },
  { id: "fu-002", patientId: "pt-002", patientName: "Ethan Brooks", doctorId: "usr-003", doctorName: "Dr. Raj Patel", dueDate: "2026-04-19", reason: "Post-laser review - assess healing after session 3", status: "PENDING", createdAt: "2026-04-05" },
  { id: "fu-003", patientId: "pt-006", patientName: "Noah Davis", doctorId: "usr-002", doctorName: "Dr. Emily Chen", dueDate: "2026-04-05", reason: "Review sunscreen adherence and IPL treatment plan", status: "PENDING", createdAt: "2026-03-30" },
  { id: "fu-004", patientId: "pt-008", patientName: "Mason Brown", doctorId: "usr-009", doctorName: "Dr. Mark Williams", dueDate: "2026-04-03", reason: "PRP therapy outcome check", status: "MISSED", createdAt: "2026-03-20" },
  { id: "fu-005", patientId: "pt-010", patientName: "Charlotte Lee", doctorId: "usr-002", doctorName: "Dr. Emily Chen", dueDate: "2026-04-08", reason: "Package progress - HydraFacial results assessment", status: "PENDING", createdAt: "2026-04-01" },
  { id: "fu-006", patientId: "pt-003", patientName: "Sophia Martinez", doctorId: "usr-002", doctorName: "Dr. Emily Chen", dueDate: "2026-03-25", reason: "Post-peel recovery check", status: "COMPLETED", completedAt: "2026-03-25", createdAt: "2026-03-15" },
  { id: "fu-007", patientId: "pt-009", patientName: "Emma Wilson", doctorId: "usr-003", doctorName: "Dr. Raj Patel", dueDate: "2026-04-11", reason: "Rosacea medication effectiveness review", status: "PENDING", createdAt: "2026-04-04" },
  { id: "fu-008", patientId: "pt-014", patientName: "Amelia Moore", doctorId: "usr-009", doctorName: "Dr. Mark Williams", dueDate: "2026-04-12", reason: "TCA peel healing assessment", status: "PENDING", createdAt: "2026-04-05" },
];

// ---- Notifications ----
export const mockNotifications: Notification[] = [
  { id: "notif-001", userId: "usr-001", title: "New Patient Registration", message: "Ella Clark (PT-0018) has been registered", type: "SYSTEM", isRead: false, link: "/patients/pt-018", createdAt: "2026-04-05T08:45:00" },
  { id: "notif-002", userId: "usr-001", title: "Appointment No-Show", message: "James Anderson missed his 9:00 AM appointment", type: "APPOINTMENT", isRead: false, link: "/appointments", createdAt: "2026-04-05T09:15:00" },
  { id: "notif-003", userId: "usr-001", title: "Overdue Invoice", message: "Invoice INV-2026-0004 for Liam Johnson is overdue (Rs 856)", type: "BILLING", isRead: false, link: "/billing/inv-004", createdAt: "2026-04-05T08:00:00" },
  { id: "notif-004", userId: "usr-001", title: "Lab Results Ready", message: "Patch test results ready for Olivia Harper", type: "LAB", isRead: true, link: "/patients/pt-001", createdAt: "2026-04-04T16:30:00" },
  { id: "notif-005", userId: "usr-002", title: "Upcoming Appointment", message: "Emma Wilson - Rosacea consultation at 10:00 AM", type: "APPOINTMENT", isRead: false, link: "/appointments/apt-004", createdAt: "2026-04-05T07:30:00" },
  { id: "notif-006", userId: "usr-001", title: "Follow-Up Due", message: "3 follow-ups are due today", type: "FOLLOW_UP", isRead: false, link: "/follow-ups", createdAt: "2026-04-05T08:00:00" },
  { id: "notif-007", userId: "usr-001", title: "Low Stock Alert", message: "Sunscreen SPF 50 is running low (5 units left)", type: "ALERT", isRead: true, createdAt: "2026-04-04T14:00:00" },
];

// ---- Call Logs ----
export const mockCallLogs: CallLog[] = [
  { id: "cl-001", leadId: "ld-001", callerName: "Rebecca Stone", userId: "usr-007", agentName: "Sophie Taylor", type: "INBOUND", duration: 180, notes: "Interested in acne treatment, asked about pricing", outcome: "CALLBACK", createdAt: "2026-04-05T09:15:00" },
  { id: "cl-002", leadId: "ld-002", callerName: "Michael Foster", userId: "usr-007", agentName: "Sophie Taylor", type: "OUTBOUND", duration: 300, notes: "Called back about Botox inquiry, explained procedure", outcome: "CALLBACK", createdAt: "2026-04-05T08:30:00" },
  { id: "cl-003", leadId: "ld-003", callerName: "Jessica Wright", userId: "usr-007", agentName: "Sophie Taylor", type: "OUTBOUND", duration: 420, notes: "Discussed laser treatment options and pricing", outcome: "BOOKED", createdAt: "2026-04-04T16:00:00" },
  { id: "cl-004", patientId: "pt-001", callerName: "Olivia Harper", userId: "usr-007", agentName: "Sophie Taylor", type: "INBOUND", duration: 120, notes: "Confirmed follow-up appointment", outcome: "INFO_PROVIDED", createdAt: "2026-04-04T11:00:00" },
  { id: "cl-005", leadId: "ld-005", callerName: "Diana Murphy", userId: "usr-007", agentName: "Sophie Taylor", type: "INBOUND", duration: 60, notes: "Asked about chemical peel pricing", outcome: "NOT_INTERESTED", createdAt: "2026-04-01T15:30:00" },
];

// ---- Consultation Notes ----
export const mockConsultationNotes: ConsultationNote[] = [
  { id: "cn-001", appointmentId: "apt-001", patientId: "pt-001", doctorId: "usr-002", doctorName: "Dr. Emily Chen", chiefComplaint: "Follow-up on acne treatment - 2 week check", symptoms: "Mild dryness around chin, slight peeling on forehead. Acne lesions reducing.", examination: "Skin appears less inflamed. Active lesion count reduced from 12 to 5. No new cystic acne. Mild retinoid dermatitis on forehead.", diagnosis: "Acne Vulgaris - Improving on current regimen", treatmentPlan: "Continue tretinoin 0.025% nightly. Add moisturizer before tretinoin. Reduce frequency to every other night if irritation persists.", advice: "Use SPF 50 daily. Avoid picking at skin. Keep skin hydrated.", followUpDate: "2026-04-19", followUpNotes: "Review in 2 weeks, consider increasing tretinoin strength if tolerated", createdAt: "2026-04-05T09:25:00" },
  { id: "cn-002", appointmentId: "apt-002", patientId: "pt-002", doctorId: "usr-003", doctorName: "Dr. Raj Patel", chiefComplaint: "Laser resurfacing session 3 of 6 for acne scarring", symptoms: "Patient reports improvement after sessions 1 and 2. Scarring less prominent.", examination: "Box car scars on cheeks showing 30% improvement. Ice pick scars stable. Skin healed well from previous session.", diagnosis: "Post-inflammatory scarring - Progressive improvement", treatmentPlan: "Proceed with Fractional CO2 Laser session 3. Energy level: 25mJ, density: 15%. Focus on bilateral cheeks and temples.", advice: "Strict sun avoidance for 2 weeks. Apply prescribed healing cream 3x daily. No exfoliating products for 10 days.", followUpDate: "2026-04-19", createdAt: "2026-04-05T09:40:00" },
];

// ---- Recent Activities (for dashboards) ----
export const mockActivities: ActivityItem[] = [
  { id: "act-001", user: "Dr. Emily Chen", action: "completed consultation", target: "Olivia Harper (PT-0001)", time: "2026-04-05T09:25:00", type: "consultation" },
  { id: "act-002", user: "Maria Santos", action: "checked in", target: "Emma Wilson (PT-0009)", time: "2026-04-05T09:52:00", type: "checkin" },
  { id: "act-003", user: "James Wilson", action: "created invoice", target: "INV-2026-0002 - Rs 481", time: "2026-04-05T09:30:00", type: "billing" },
  { id: "act-004", user: "Sophie Taylor", action: "logged call with", target: "Rebecca Stone (Lead)", time: "2026-04-05T09:15:00", type: "call" },
  { id: "act-005", user: "Dr. Raj Patel", action: "started procedure", target: "Ethan Brooks - CO2 Laser", time: "2026-04-05T09:00:00", type: "procedure" },
  { id: "act-006", user: "Rachel Green", action: "recorded vitals for", target: "Ava Williams (PT-0005)", time: "2026-04-05T09:45:00", type: "vitals" },
  { id: "act-007", user: "Maria Santos", action: "registered new patient", target: "PT-0020 - Grace Robinson", time: "2026-04-05T08:30:00", type: "registration" },
  { id: "act-008", user: "System", action: "marked no-show", target: "James Anderson (APT-0016)", time: "2026-04-05T09:15:00", type: "system" },
];

// ---- Lab Tests ----
export const mockLabTests: LabTest[] = [
  { id: "lt-001", patientId: "pt-001", patientName: "Olivia Harper", doctorId: "usr-002", doctorName: "Dr. Emily Chen", testName: "Patch Test - Allergen Panel", status: LabTestStatus.COMPLETED, results: { allergens: ["Salicylic Acid", "Latex"], interpretation: "Positive for salicylic acid and latex" }, technician: "Lab Tech A", completedAt: "2026-04-04T16:00:00", notes: "Standard 48-hour patch test", createdAt: "2026-04-02" },
  { id: "lt-002", patientId: "pt-002", patientName: "Ethan Brooks", doctorId: "usr-003", doctorName: "Dr. Raj Patel", testName: "Blood Work - CBC + Hormones", status: LabTestStatus.PROCESSING, technician: "Lab Tech B", collectedAt: "2026-04-04T10:00:00", createdAt: "2026-04-04" },
  { id: "lt-003", patientId: "pt-005", patientName: "Ava Williams", doctorId: "usr-003", doctorName: "Dr. Raj Patel", testName: "Skin Biopsy - Pigmented Lesion", status: LabTestStatus.REQUESTED, notes: "Suspicious mole on left shoulder", createdAt: "2026-04-05" },
  { id: "lt-004", patientId: "pt-009", patientName: "Emma Wilson", doctorId: "usr-003", doctorName: "Dr. Raj Patel", testName: "Allergy Panel - Skincare Products", status: LabTestStatus.SAMPLE_COLLECTED, technician: "Lab Tech A", collectedAt: "2026-04-05T08:30:00", createdAt: "2026-04-04" },
  { id: "lt-005", patientId: "pt-015", patientName: "Lucas Jackson", doctorId: "usr-002", doctorName: "Dr. Emily Chen", testName: "Hormone Panel - Acne Related", status: LabTestStatus.COMPLETED, results: { testosterone: "Normal", dhea_s: "Slightly elevated", cortisol: "Normal" }, technician: "Lab Tech B", completedAt: "2026-04-03T14:00:00", createdAt: "2026-04-01" },
];

// ---- Triage Records ----
export const mockTriageRecords: Triage[] = [
  { id: "tri-001", patientId: "pt-005", patientName: "Ava Williams", appointmentId: "apt-003", temperature: 36.8, systolicBP: 120, diastolicBP: 80, heartRate: 72, respiratoryRate: 16, weight: 58, height: 165, oxygenSaturation: 98, bmi: "21.3", notes: "Patient appears healthy. No concerns.", urgencyLevel: "NORMAL", recordedById: "usr-008", recordedByName: "Rachel Green", createdAt: "2026-04-05T09:45:00" },
  { id: "tri-002", patientId: "pt-009", patientName: "Emma Wilson", appointmentId: "apt-004", temperature: 36.6, systolicBP: 115, diastolicBP: 75, heartRate: 68, weight: 62, height: 170, oxygenSaturation: 99, bmi: "21.5", notes: "Slight redness on cheeks - rosacea flare", skinObservations: "Papulopustular rosacea on bilateral cheeks, erythema extending to nose", urgencyLevel: "NORMAL", recordedById: "usr-008", recordedByName: "Rachel Green", createdAt: "2026-04-05T09:55:00" },
];

// ---- AI Transcriptions ----
export const mockAITranscriptions: AITranscription[] = [
  { id: "ai-001", appointmentId: "apt-001", patientId: "pt-001", patientName: "Olivia Harper", doctorId: "usr-002", doctorName: "Dr. Emily Chen", rawTranscript: "Doctor: How has your skin been since we started the tretinoin?\nPatient: Much better, the breakouts have reduced a lot. But I do get some dryness and peeling on my forehead.\nDoctor: That's normal with retinoids. Let me take a look... Yes, I can see the retinoid dermatitis on your forehead. The good news is your active acne has reduced significantly.\nPatient: Should I keep using it every night?\nDoctor: Let's reduce to every other night and add a moisturizer before applying. This should help with the irritation while maintaining the benefits.", structuredNote: { chiefComplaint: "Follow-up acne treatment", findings: "Reduced acne, mild retinoid dermatitis", plan: "Reduce tretinoin frequency, add moisturizer" }, summary: "Patient showing improvement on tretinoin with mild side effects. Adjusted application frequency.", status: "COMPLETED", duration: 480, createdAt: "2026-04-05T09:25:00" },
];

// ---- Audit Log ----
export const mockAuditLogs: AuditLog[] = [
  { id: "al-001", userId: "usr-005", userName: "Maria Santos", action: "CREATE", module: "PATIENT", entityType: "Patient", entityId: "pt-020", details: "Registered new patient: Grace Robinson", ipAddress: "192.168.1.105", createdAt: "2026-04-05T08:30:00" },
  { id: "al-002", userId: "usr-002", userName: "Dr. Emily Chen", action: "CREATE", module: "CONSULTATION", entityType: "ConsultationNote", entityId: "cn-001", details: "Created consultation note for Olivia Harper", ipAddress: "192.168.1.110", createdAt: "2026-04-05T09:25:00" },
  { id: "al-003", userId: "usr-006", userName: "James Wilson", action: "CREATE", module: "BILLING", entityType: "Invoice", entityId: "inv-002", details: "Created invoice INV-2026-0002 - Rs 481", ipAddress: "192.168.1.108", createdAt: "2026-04-05T09:30:00" },
  { id: "al-004", userId: "usr-001", userName: "Dr. Sarah Mitchell", action: "LOGIN", module: "AUTH", entityType: "Session", entityId: "sess-001", details: "Admin login", ipAddress: "192.168.1.100", createdAt: "2026-04-05T08:30:00" },
  { id: "al-005", userId: "usr-007", userName: "Sophie Taylor", action: "CREATE", module: "CALL_CENTER", entityType: "Lead", entityId: "ld-001", details: "Created new lead: Rebecca Stone", ipAddress: "192.168.1.112", createdAt: "2026-04-05T09:15:00" },
];

// ---- Patient Documents ----
export const mockDocuments: PatientDocument[] = [
  { id: "doc-001", patientId: "pt-001", name: "Patch Test Report.pdf", type: DocumentType.LAB_RESULT, fileUrl: "/uploads/doc-001.pdf", fileSize: 245000, uploadedById: "usr-002", uploadedByName: "Dr. Emily Chen", notes: "Allergen panel results", createdAt: "2026-04-04" },
  { id: "doc-002", patientId: "pt-001", name: "Treatment Consent Form.pdf", type: DocumentType.CONSENT, fileUrl: "/uploads/doc-002.pdf", fileSize: 180000, uploadedById: "usr-005", uploadedByName: "Maria Santos", createdAt: "2026-03-14" },
  { id: "doc-003", patientId: "pt-002", name: "Before - Acne Scarring.jpg", type: DocumentType.BEFORE_AFTER, fileUrl: "/uploads/doc-003.jpg", fileSize: 1200000, uploadedById: "usr-003", uploadedByName: "Dr. Raj Patel", notes: "Baseline photo before laser treatment", createdAt: "2026-02-15" },
  { id: "doc-004", patientId: "pt-002", name: "After Session 2 - Scarring.jpg", type: DocumentType.BEFORE_AFTER, fileUrl: "/uploads/doc-004.jpg", fileSize: 1150000, uploadedById: "usr-003", uploadedByName: "Dr. Raj Patel", notes: "Progress after 2 CO2 laser sessions", createdAt: "2026-03-20" },
  { id: "doc-005", patientId: "pt-009", name: "Referral Letter.pdf", type: DocumentType.REPORT, fileUrl: "/uploads/doc-005.pdf", fileSize: 95000, uploadedById: "usr-005", uploadedByName: "Maria Santos", createdAt: "2026-04-04" },
];

// ---- Communication Logs ----
export const mockCommunicationLogs: CommunicationLog[] = [
  { id: "comm-001", patientId: "pt-001", type: "CALL", direction: "OUTBOUND", subject: "Appointment Reminder", content: "Called to remind about follow-up appointment on April 5", sentById: "usr-005", sentByName: "Maria Santos", createdAt: "2026-04-04T10:00:00" },
  { id: "comm-002", patientId: "pt-001", type: "SMS", direction: "OUTBOUND", subject: "Appointment Confirmation", content: "Your appointment with Dr. Emily Chen on April 5 at 9:00 AM is confirmed.", sentById: "usr-005", sentByName: "Maria Santos", createdAt: "2026-04-03T16:00:00" },
  { id: "comm-003", patientId: "pt-004", type: "EMAIL", direction: "OUTBOUND", subject: "Invoice Reminder", content: "Gentle reminder: Invoice INV-2026-0004 (Rs 856) is overdue. Please contact us for payment arrangements.", sentById: "usr-006", sentByName: "James Wilson", createdAt: "2026-04-01T09:00:00" },
  { id: "comm-004", patientId: "pt-010", type: "WHATSAPP", direction: "OUTBOUND", subject: "Package Update", content: "Hi Charlotte! You have 2 HydraFacial sessions remaining in your Glow Up Package. Would you like to book your next session?", sentById: "usr-005", sentByName: "Maria Santos", createdAt: "2026-04-02T14:00:00" },
];

// ---- Skin History ----
export const mockSkinHistory: SkinHistory[] = [
  { id: "sh-001", patientId: "pt-001", condition: "Acne Vulgaris", affectedArea: "Face - Chin, Forehead", severity: "MODERATE", onsetDate: "2024-06-01", treatmentHistory: "Benzoyl peroxide (OTC), Clindamycin gel (3 months), Tretinoin (current)", notes: "Hormonal pattern. Worsens with stress and before menstruation.", images: [] },
  { id: "sh-002", patientId: "pt-002", condition: "Post-inflammatory Scarring", affectedArea: "Face - Bilateral Cheeks, Temples", severity: "MODERATE", onsetDate: "2023-01-01", treatmentHistory: "Microneedling (2 sessions, mild improvement), CO2 Laser (3 sessions, ongoing)", notes: "Box car and ice pick scars from severe acne in teens. Good response to laser.", images: [] },
  { id: "sh-003", patientId: "pt-005", condition: "Hyperpigmentation / Melasma", affectedArea: "Face - Forehead, Upper Lip, Cheeks", severity: "MILD", onsetDate: "2025-08-01", treatmentHistory: "New patient - no prior treatment", notes: "Onset after summer sun exposure. Considering combination approach.", images: [] },
];

// ---- Medical History ----
export const mockMedicalHistory: MedicalHistory[] = [
  { id: "mh-001", patientId: "pt-001", condition: "Polycystic Ovary Syndrome (PCOS)", diagnosedDate: "2020-03-01", status: "CHRONIC", notes: "Contributing to hormonal acne. On birth control for management." },
  { id: "mh-002", patientId: "pt-004", condition: "Hypertension (mild)", diagnosedDate: "2022-06-01", status: "ACTIVE", notes: "Controlled with medication. Consider when planning procedures." },
  { id: "mh-003", patientId: "pt-009", condition: "Seasonal Allergies", diagnosedDate: "2018-01-01", status: "CHRONIC", notes: "May affect skin sensitivity during spring months." },
];

// ---- Prescriptions ----
export const mockPrescriptions: Prescription[] = [
  { id: "rx-001", patientId: "pt-001", doctorId: "usr-002", doctorName: "Dr. Emily Chen", appointmentId: "apt-001", items: [
    { id: "rxi-001", medicineName: "Tretinoin Cream 0.025%", dosage: "Pea-sized amount", frequency: "Every other night", duration: "3 months", instructions: "Apply to clean, dry face. Avoid eye area. Use after moisturizer." },
    { id: "rxi-002", medicineName: "Clindamycin Phosphate Gel 1%", dosage: "Thin layer", frequency: "Twice daily", duration: "3 months", instructions: "Apply to affected areas morning and evening" },
    { id: "rxi-003", medicineName: "Cetaphil Moisturizer", dosage: "As needed", frequency: "Twice daily", duration: "Ongoing", instructions: "Apply before tretinoin at night, and morning after cleansing" },
  ], notes: "Reduced tretinoin to every other night due to irritation. Review in 2 weeks.", createdAt: "2026-04-05" },
  { id: "rx-002", patientId: "pt-009", doctorId: "usr-003", doctorName: "Dr. Raj Patel", items: [
    { id: "rxi-004", medicineName: "Metronidazole Gel 0.75%", dosage: "Thin layer", frequency: "Twice daily", duration: "2 months", instructions: "Apply to affected rosacea areas" },
    { id: "rxi-005", medicineName: "Sunscreen SPF 50+ (mineral)", dosage: "Generous amount", frequency: "Every 2 hours when outdoors", duration: "Ongoing", instructions: "Zinc oxide or titanium dioxide based. Reapply frequently." },
  ], createdAt: "2026-04-04" },
];

// ---- Patient Packages ----
export const mockPatientPackages: PatientPackage[] = [
  { id: "pp-001", patientId: "pt-010", packageId: "pkg-001", packageName: "Glow Up Package", purchaseDate: "2025-12-01", expiryDate: "2026-05-30", remainingSessions: { "HydraFacial": 2, "Glycolic Acid Peel": 1 }, status: "ACTIVE", invoiceId: "inv-pkg-001" },
  { id: "pp-002", patientId: "pt-001", packageId: "pkg-002", packageName: "Acne Clear Plan", purchaseDate: "2026-01-15", expiryDate: "2026-05-15", remainingSessions: { "LED Light Therapy": 4, "Glycolic Acid Peel": 2 }, status: "ACTIVE", invoiceId: "inv-pkg-002" },
  { id: "pp-003", patientId: "pt-004", packageId: "pkg-003", packageName: "Anti-Aging Premium", purchaseDate: "2025-11-01", expiryDate: "2026-10-31", remainingSessions: { "Botox": 1, "Dermal Fillers": 1, "Fractional CO2 Laser": 2 }, status: "ACTIVE", invoiceId: "inv-pkg-003" },
];

// ---- Room Allocations ----
export const mockRoomAllocations: RoomAllocation[] = [
  { id: "ra-001", patientId: "pt-001", patientName: "Olivia Harper", roomId: "rm-001", roomName: "Room 1 - Consultation", doctorId: "usr-002", doctorName: "Dr. Emily Chen", admissionDate: "2026-04-05T09:00:00", status: "ACTIVE" },
  { id: "ra-002", patientId: "pt-002", patientName: "Ethan Brooks", roomId: "rm-002", roomName: "Room 2 - Laser Suite", doctorId: "usr-003", doctorName: "Dr. Raj Patel", admissionDate: "2026-04-05T09:00:00", status: "ACTIVE" },
  { id: "ra-003", patientId: "pt-014", patientName: "Amelia Moore", roomId: "rm-009", roomName: "Room 1 - Multi-Purpose", doctorId: "usr-009", doctorName: "Dr. Mark Williams", admissionDate: "2026-04-05T09:30:00", status: "ACTIVE" },
];
