/**
 * @system MediCore ERP — Continuity briefing
 * @route GET /api/patients/:id/continuity-briefing
 *
 * Returns a 1-2 sentence summary of the patient's recent clinical
 * activity, generated by extractive AI over the last 2 consultation
 * notes + last prescription + open lab orders + pending follow-ups.
 *
 * Rendered at the top of the doctor-app patient detail screen so
 * the doctor sees the bridge from "last time" to "this time" before
 * scrolling to history. Strictly extractive: the prompt forbids
 * inference, hallucination, or alternative suggestions. If there is
 * no history (new patient), the route returns success=true with
 * data.briefing=null — the UI hides the card.
 *
 * Caching: not yet — the briefing is computed on every open. If
 * cost becomes an issue, persist the result with an inputHash and
 * skip recompute when nothing's changed.
 */
import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireAuth } from "@/lib/require-auth";
import { logger } from "@/lib/logger";
import { checkRateLimit, RATE_LIMITS } from "@/lib/rate-limit";
import { PROMPT_VERSIONS, AMBIENT_MODEL_ID } from "@/lib/ai-suggestion";

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

const SYSTEM_PROMPT = `You write a single 1-2 sentence continuity briefing for a dermatology doctor opening a patient profile.

You are given structured JSON of the patient's recent clinical activity (last visits, prescriptions, open labs, pending follow-ups, last visit date).

Rules:
- 1 to 2 sentences only. No bullets, no markdown.
- Past tense for completed activity, present tense for open items.
- Doctor's voice — terse, telegraphic, like a colleague's handover.
- Only include information that is in the input. Do NOT speculate, suggest next steps, or fill gaps.
- If the input is empty (new patient with no history), reply exactly: "No prior visits."
- Never use the patient's name (the UI already shows it).

Style examples:
- "Last seen 14 days ago for moderate acne — started Adapalene 0.3% + Doxycycline. LFT pending. Two-week follow-up due today."
- "Three visits for melasma over past 4 months. Current regimen: Hydroquinone 4% + Tretinoin 0.025%. Last review noted moderate improvement."
- "First-time patient. No prior visits."`;

interface BriefingInput {
  visits: Array<{ date: string; chiefComplaint: string | null; diagnosis: string | null; plan: string | null }>;
  prescriptions: Array<{ date: string; items: Array<{ name: string; dosage: string | null; frequency: string | null }> }>;
  openLabs: Array<{ name: string; status: string; orderedAt: string }>;
  pendingFollowUps: Array<{ reason: string; dueDate: string }>;
  lastVisitDaysAgo: number | null;
}

export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const auth = await requireAuth();
    if (auth.response) return auth.response;

    // Cheaper than transcription but still hits OpenAI. Same
    // rationale: bound the per-user spend ceiling.
    const rl = checkRateLimit(auth.user.id, RATE_LIMITS.AI_BRIEFING);
    if (!rl.ok) {
      // Briefing is best-effort UI candy; degrade silently with no
      // briefing rather than blocking the whole patient open.
      return NextResponse.json({
        success: true,
        data: { briefing: null, modelId: null, promptVersion: null, computedAt: null, rateLimited: true },
      });
    }

    const { id } = await params;

    // Pull all input slices in parallel. Each is bounded so the
    // briefing prompt never balloons.
    const [notes, lastRx, openLabs, openFollowUps] = await Promise.all([
      prisma.consultationNote.findMany({
        where: { patientId: id },
        orderBy: { createdAt: "desc" },
        take: 2,
        select: {
          createdAt: true,
          chiefComplaint: true,
          diagnosis: true,
          treatmentPlan: true,
        },
      }),
      prisma.prescription.findFirst({
        where: { patientId: id },
        orderBy: { createdAt: "desc" },
        select: {
          createdAt: true,
          items: { select: { medicineName: true, dosage: true, frequency: true } },
        },
      }),
      prisma.labTest.findMany({
        where: {
          patientId: id,
          status: { notIn: ["COMPLETED", "CANCELLED"] },
        },
        orderBy: { createdAt: "desc" },
        take: 5,
        select: { testName: true, status: true, createdAt: true },
      }),
      prisma.followUp.findMany({
        where: { patientId: id, status: "PENDING" },
        orderBy: { dueDate: "asc" },
        take: 3,
        select: { reason: true, dueDate: true },
      }),
    ]);

    if (
      notes.length === 0
      && (!lastRx || lastRx.items.length === 0)
      && openLabs.length === 0
      && openFollowUps.length === 0
    ) {
      // No history at all — short-circuit, no AI call.
      return NextResponse.json({
        success: true,
        data: { briefing: null, modelId: null, promptVersion: null, computedAt: null },
      });
    }

    const lastVisitDaysAgo = notes.length > 0
      ? Math.max(0, Math.round((Date.now() - notes[0].createdAt.getTime()) / 86400000))
      : null;

    const input: BriefingInput = {
      visits: notes.map((n) => ({
        date: n.createdAt.toISOString().slice(0, 10),
        chiefComplaint: n.chiefComplaint,
        diagnosis: n.diagnosis,
        plan: n.treatmentPlan,
      })),
      prescriptions: lastRx
        ? [{
            date: lastRx.createdAt.toISOString().slice(0, 10),
            items: lastRx.items.slice(0, 6).map((i) => ({
              name: i.medicineName,
              dosage: i.dosage,
              frequency: i.frequency,
            })),
          }]
        : [],
      openLabs: openLabs.map((l) => ({
        name: l.testName,
        status: l.status,
        orderedAt: l.createdAt.toISOString().slice(0, 10),
      })),
      pendingFollowUps: openFollowUps.map((f) => ({
        reason: f.reason,
        dueDate: f.dueDate.toISOString().slice(0, 10),
      })),
      lastVisitDaysAgo,
    };

    if (!OPENAI_API_KEY) {
      // Fallback: render a deterministic briefing from the structured
      // input so the surface still works without OpenAI.
      const briefing = renderFallback(input);
      return NextResponse.json({
        success: true,
        data: {
          briefing,
          modelId: "fallback-deterministic",
          promptVersion: PROMPT_VERSIONS.CONTINUITY_BRIEFING_V1,
          computedAt: new Date().toISOString(),
        },
      });
    }

    const aiRes = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${OPENAI_API_KEY}` },
      body: JSON.stringify({
        model: AMBIENT_MODEL_ID,
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: JSON.stringify(input) },
        ],
        max_tokens: 200,
        temperature: 0.2,
      }),
    });

    if (!aiRes.ok) {
      // Graceful: fall back to the deterministic renderer.
      const briefing = renderFallback(input);
      return NextResponse.json({
        success: true,
        data: {
          briefing,
          modelId: "fallback-deterministic",
          promptVersion: PROMPT_VERSIONS.CONTINUITY_BRIEFING_V1,
          computedAt: new Date().toISOString(),
        },
      });
    }
    const aiData = await aiRes.json();
    const briefing = (aiData.choices?.[0]?.message?.content || "").trim() || renderFallback(input);

    return NextResponse.json({
      success: true,
      data: {
        briefing,
        modelId: AMBIENT_MODEL_ID,
        promptVersion: PROMPT_VERSIONS.CONTINUITY_BRIEFING_V1,
        computedAt: new Date().toISOString(),
      },
    });
  } catch (error) {
    logger.api("GET", "/api/patients/[id]/continuity-briefing", error);
    return NextResponse.json(
      { success: false, error: "Failed to generate briefing" },
      { status: 500 },
    );
  }
}

/**
 * Deterministic fallback when OpenAI is unavailable. Composes a
 * terse English summary from the structured input. Not as fluent
 * as the AI version but always extractive — never invents content.
 */
function renderFallback(i: BriefingInput): string {
  const parts: string[] = [];
  if (i.visits.length > 0) {
    const v = i.visits[0];
    const dx = v.diagnosis ? ` for ${v.diagnosis}` : v.chiefComplaint ? ` for ${v.chiefComplaint}` : "";
    const ago = i.lastVisitDaysAgo === 0 ? "earlier today" : i.lastVisitDaysAgo === 1 ? "yesterday" : `${i.lastVisitDaysAgo} days ago`;
    parts.push(`Last seen ${ago}${dx}.`);
  }
  if (i.prescriptions.length > 0) {
    const items = i.prescriptions[0].items.slice(0, 3).map((x) => x.name).join(", ");
    if (items) parts.push(`Current regimen: ${items}.`);
  }
  if (i.openLabs.length > 0) {
    const labs = i.openLabs.slice(0, 3).map((l) => `${l.name} (${l.status.toLowerCase().replace(/_/g, " ")})`).join(", ");
    parts.push(`Open labs: ${labs}.`);
  }
  if (i.pendingFollowUps.length > 0) {
    const f = i.pendingFollowUps[0];
    parts.push(`Follow-up due ${f.dueDate}: ${f.reason}.`);
  }
  return parts.length > 0 ? parts.join(" ") : "No prior visits.";
}
